--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-25-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "TEST7"."NOTICE" 
   (	"NOTI_IDX" NUMBER(20,0), 
	"NOTI_TITLE" VARCHAR2(100 BYTE), 
	"NOTI_CONTENT" VARCHAR2(1000 BYTE), 
	"NOTI_AUTHOR" VARCHAR2(20 BYTE) DEFAULT '관리자', 
	"NOTI_FILE" VARCHAR2(200 BYTE), 
	"NOTI_REGDATE" DATE DEFAULT current_timestamp   -- 작성일                     

   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TEST7.NOTICE
SET DEFINE OFF;
Insert into TEST7.NOTICE (NOTI_IDX,NOTI_TITLE,NOTI_CONTENT,NOTI_AUTHOR,NOTI_FILE,NOTI_REGDATE) values (1,'공지1','공지내용1','관리자','spring.png',to_date('23/07/21','RR/MM/DD'));
Insert into TEST7.NOTICE (NOTI_IDX,NOTI_TITLE,NOTI_CONTENT,NOTI_AUTHOR,NOTI_FILE,NOTI_REGDATE) values (4,'테스트입니다4','444444','관리자','1689907168351_스크린샷(1).png',to_date('23/07/21','RR/MM/DD'));
Insert into TEST7.NOTICE (NOTI_IDX,NOTI_TITLE,NOTI_CONTENT,NOTI_AUTHOR,NOTI_FILE,NOTI_REGDATE) values (3,'테스트입니다.3','3333','관리자','1689906069641_스크린샷(2).png',to_date('23/07/21','RR/MM/DD'));
Insert into TEST7.NOTICE (NOTI_IDX,NOTI_TITLE,NOTI_CONTENT,NOTI_AUTHOR,NOTI_FILE,NOTI_REGDATE) values (5,'공지사항 테스트12','공지사항 테스트12','admin','1690249454335_spring.png',to_date('23/07/25','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007350
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST7"."SYS_C007350" ON "TEST7"."NOTICE" ("NOTI_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "TEST7"."NOTICE" ADD PRIMARY KEY ("NOTI_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST7"."NOTICE" MODIFY ("NOTI_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "TEST7"."NOTICE" MODIFY ("NOTI_TITLE" NOT NULL ENABLE);
  ALTER TABLE "TEST7"."NOTICE" MODIFY ("NOTI_IDX" NOT NULL ENABLE);

CREATE SEQUENCE NOTI_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;